### ISSUE TITLE
Adding a Keyword environment

### ISSUE THREAD

**Issue by aubertc** [Jinwen-XU/minimalist#2]
I believe it would not be too difficult to adapt the code for the abtract (https://github.com/Jinwen-XU/minimalist/blob/407adcd4dcf124c900eeecf20bf2166dd9f6604a/minimalist.dtx#L955-L994) to provide a `keyword` environment.

I have "hacked" something of the like:

![image](https://user-images.githubusercontent.com/16466689/118373006-6cc29700-b582-11eb-91ce-16c2e4025e79.png)

and can open a pull request if there is an agreement that this would be a useful feature.

**Comment by Jinwen-XU** [comment]
Thanks for your suggestion, the `keyword` environment has been added in [Update 2021-05-19a](https://github.com/Jinwen-XU/minimalist/commit/f4a8426944ee60d7d0f8e5fff63c33298cd08c4f).

By the way, there is a `\keywords` command similar to that of the `amsart` class.

**Comment by aubertc** [comment]
Thanks a lot!
You should use and introduce it in https://github.com/Jinwen-XU/minimalist/blob/main/minimalist/minimalist-doc.tex now!

I can make a pull request addressing that if you want.

**Comment by Jinwen-XU** [comment]
In fact, I'm working on rewriting all the documentation, which should be completed in the next few days, due to the fact that the code structure has changed considerably from the last time I wrote the documentation.
