### ISSUE TITLE
Japanese font is not correctly selected

### ISSUE THREAD

**Issue by mlmbl** [Jinwen-XU/minimalist#3]
When a document containing Japanese characters is compiled, Chinese fonts are embedded in the Japanese portion of the document and some characters are not displayed correctly. Is there a way to explicitly specify the language of the document?

**Comment by Jinwen-XU** [comment]
Yes, it is via `\UseLanguage` (globally), or `\UseOtherLanguage` (locally).

> The name `\UseOtherLanguage` seems rather unclear, in the next version I shall also add two equivalent commands under the name `\LocallyUseLanguage` and `\UseLanguageLocally` so that you may choose a preferred one to use.

Here is an example:

```latex
\documentclass[use indent = false]{einfart}

\AddLanguageSetting[Japanese]{\color{blue}} % Blue for Japanese
\AddLanguageSetting{\color{black}}          % Black in general

\begin{document}

字 % By default it uses the Simplified Chinese glyph, as you observed

\UseLanguage{Japanese} % Switch to Japanese, it is also possible to write "JP"

字

\UseLanguage{Chinese} % Switch to Simplified Chinese

字 \UseOtherLanguage{Japanese}{字} % Locally write in Japanese

%% ONLY WITH THE NEXT VERSION
% \LocallyUseLanguage{Japanese}{字}
% \UseLanguageLocally{Japanese}{字}

\end{document}
```

I have set the Japanese characters to be rendered in color blue, so the result looks like this:

<img width="385" alt="image" src="https://github.com/Jinwen-XU/minimalist/assets/80377812/366c1b6b-0a7f-450f-9bea-daefa340d8a6">

> I hope that I could finish writing the documentation soon, until then I shall leave this Issue open.

**Comment by mlmbl** [comment]
Thank you for your advice.  By explicitly specifying the language, proper fonts are selected automatically. Thanks again.
